#Application URL
url_old=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url=http://localhost/orangehrm/web/index.php/auth/login
#Browser Configuration
browser=chrome
#Credentials
username=orangeHRm_Satabdi
password=orangeHRm_Satabdi2000
#ImplicitWait(in seconds)
implicitWait=10
explicitWait=30

